### ISSUE TITLE
Programar menú pausa

### ISSUE THREAD

**Issue by Folch** [eloipuertas/ES2014B#100]
Per tal de que l'usuari pugui pausar el joc s'oferirà la possibilitat de fer-ho apretant el botó ESC un cop.

7 hores estimades

Condició de finalització: Que s'ofereixin com a mínim, al apretar el botó ESC, les opcions de continuar i tornar al menú principal. (en un altre sprint o en aquest si dóna temps s'oferiran també les opcions de pausar/reproduir la música i més endavant potser guardar/carregar partida).

**Comment by xaviml** [comment]
Tot i que estigui programada aquesta part, quan vegi un menú al apretar 'ESC', tancaré aquesta issue. La marco de moment per al següent sprint. @Folch

**Comment by xaviml** [comment]
Perdona, no havia testejat bé, canvio el milestone, i tanco issue @Folch
