### ISSUE TITLE
Create a Spell Cast Animation on the Main Character

### ISSUE THREAD

**Issue by Payetus** [eloipuertas/ES2014B#105]
## Description

Create a spell cast animation on MainCharacter.  When the character invokes a spell of fire or ice this animation should be played. The main character lifts both arms up in the air and waves them.
## Objectives

Create a spell cast animation on MainCharacter.
## Subtasks
- [x] Create a spell cast animation on MainCharacter model 8h
- [ ] Adding a new state associated with animation to the animation controller.
## TestCase
- When pressing the spell button the spell cast button should be played
## Estimated Time

Estimated time: 8 hours
## ProductBacklog

Personatje reb mal.

**Comment by pherrusa7** [comment]
@Payetus  Falten hores, descripció i condicions d'acabament.

**Comment by pherrusa7** [comment]
@Payetus Aquesta issue no hauria de parlar de la death animation i ho fa en el TestCase, modifica el copy-paste.

**Comment by Payetus** [comment]
Refactored @pherrusa7

**Comment by pherrusa7** [comment]
@Payetus Tanco issue, ja estava fet.
