### ISSUE TITLE
Create Death Animation for Main Character

### ISSUE THREAD

**Issue by Payetus** [eloipuertas/ES2014B#106]
## Description

Creates a death animation on MainCharacter.  When the character dies this animation should be played. The main character roles about and falls to the floor.
## Objectives

Creates a death animation on MainCharacter
## Subtasks
- [x] Create attacking animation on model main character 8h
## TestCase
- When pressing button 3 on keyboard the death animation  should be played.
- No more animation should be able to be played after the death animation.
## Estimated Time

Estimated time: 8 hours
## ProductBacklog

Personatje reb mal.

**Comment by pherrusa7** [comment]
@Payetus Falten hores, descripció i condicions d'acabament. No puc tancar-la.
