### ISSUE TITLE
Create Dummy Scene

### ISSUE THREAD

**Issue by Payetus** [eloipuertas/ES2014B#11]
This issue is part of environment setup, creating the Mock/Dummy scene with a Mock/Dummy Terrain where the Animator from Group A can work on. 

Estimated time :1hour

**Comment by Payetus** [comment]
This issue is not a full feature this is added to issue #14

**Comment by pherrusa7** [comment]
@Payetus No pots tancar-te les issues, només ho pot fer l'integrador del teu grup, que sóc jo.
@Payetus D'aquesta issue jo no he vist res encara, per tant, queda oberta.
