### ISSUE TITLE
C-113-aturar musica ambient pause

### ISSUE THREAD

**Issue by voriol** [eloipuertas/ES2014B#113]
Descripció: aturar musica ambient pause

Condició Finalització: Quan es seleccioni el botó pause del menú el joc, s'aturara la musica de fons

Temps estimat: 2h

**Comment by xaviml** [comment]
Segons els daily meetings aquesta issue ja està acabada. Jo al pausar al joc (presionant 'ESC') segueixo escoltant la música de fons. @voriol

**Comment by xaviml** [comment]
Paso aquesta issue per al següent sprint. @voriol

**Comment by xaviml** [comment]
Perfecte, hi ha hagut un mal entés. Ja està resolt. @voriol Tanco issue
