### ISSUE TITLE
C-115-particules PJ

### ISSUE THREAD

**Issue by voriol** [eloipuertas/ES2014B#115]
Descripció: particules PJ

Condició Finalització: El PJ ha de poder llencar particules en una direcció amb el so corresponent

Temps estimat: 8h

**Comment by xaviml** [comment]
Deixo aquesta issue per al següent Sprint @voriol

**Comment by xaviml** [comment]
He estat barallant-me una bona estona amb això com et vaig dir, però no he aconseguit cap resultat. Ho aplacem per al pròxim sprint @voriol

**Comment by voriol** [comment]
@xaviml https://github.com/xaviml: les particules dirigidos funcionen, les integro a devel-C o a devel ?

**Comment by voriol** [comment]
@aniskhoury , @xaviml , he documentat com utilitzar els scripts de magia en la pagina

https://github.com/eloipuertas/ES2014B/wiki/Magia

el sistema de particules es independent del prefarb del Player, qualsevol dubte el comentem

**Comment by xaviml** [comment]
Després de tant problemes, ja podem tancar aquesta issue. Tot un èxit @voriol.

**Comment by voriol** [comment]
ueeeeeeeee !!

gracies Xavi !

2014-12-01 22:53 GMT+01:00 Xavi notifications@github.com:

> Després de tant problemes, ja podem tancar aquesta issue. Tot un èxit
> @voriol https://github.com/voriol.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/eloipuertas/ES2014B/issues/115#issuecomment-65141568.

## 

Atentament,

Víctor Oriol i Aguilar
vkoriol@gmail.com
