### ISSUE TITLE
Diseño definitivo escenario nivel1

### ISSUE THREAD

**Issue by CristhianCarmona** [eloipuertas/ES2014B#119]
Descripcion: elaborar esbozo definitivo del escenario del nivel 1 

Horas estimadas: 1

Condicion final: adjuntar imagenes ilustrativas del escenario

**Comment by CristhianCarmona** [comment]
Se adjunta diseño nivel1

![mapa_nivel1](https://cloud.githubusercontent.com/assets/6708224/4965222/db9c58b4-6782-11e4-93a9-805218f0310c.jpg)

**Comment by xaviml** [comment]
Perfecto, considero esta issue como acabada. Además el escenario va cogiendo esta forma. Cierro issue @cctGitHub

**Comment by CristhianCarmona** [comment]
@xaviml perfecto
