### ISSUE TITLE
Adding Dummy main character

### ISSUE THREAD

**Issue by Payetus** [eloipuertas/ES2014B#12]
Adding a dummy main character to the dummy environment, this issue depends on issue #11.

Estimated time: 1 hour

**Comment by Payetus** [comment]
This issue is not a full feature this is added to issue #14

**Comment by pherrusa7** [comment]
@Payetus No pots tancar-te les issues, només ho pot fer l'integrador del teu grup, que sóc jo.
@Payetus D'aquesta issue jo no he vist res encara, per tant, queda oberta.
