### ISSUE TITLE
GameOver

### ISSUE THREAD

**Issue by Folch** [eloipuertas/ES2014B#125]
La textura del game over i el butó per tornar al menú principal s'ha de mostrar a la part superior de la pantalla per a que es pugui veure al centre el personatge principal quan mor. També s'ha d'executar les funcions de gameover del personatge principal i dels npcs.

1 hora 30 minuts estimada

Condició de finalització:
Veure el game over i el butó de tornar al menú principal al centre superior de la pantalla i que es pausi el joc

**Comment by xaviml** [comment]
Perfecte, tanco issue @Folch
