### ISSUE TITLE
Colocar al hud l'escut

### ISSUE THREAD

**Issue by Folch** [eloipuertas/ES2014B#126]
Edito (ara les pocions no es guarden, es consumeixen al agafar-les, per tant ja no tenen res a veure amb el hud i només podrem agafar un escut per millorar la nostra protecció):
El personatge principal pot recollir un escut que hi hagi pel terra que farà que sigui més fort.

5 hores estimades

Condició de finalització:
Haig de mostrar en el hud si ha agafat l'escut o no

**Comment by xaviml** [comment]
Veig un escut en el HUD, perfecte @Folch
