### ISSUE TITLE
Pausar el joc

### ISSUE THREAD

**Issue by Folch** [eloipuertas/ES2014B#127]
Quan surt el menú de pausa del joc, s'han de cridar a les funcions de pausa dels npcs i del main character.

1h 30 min estimades

Condició de finalització:
Al mostrar-se el menú de pausa el jugador i els npcs es pararan i no es podrà moure ningú.

**Comment by xaviml** [comment]
Perfecte, no permet moure res quan està en pausa o en el GameOver. Això soluciona la issue #173. Tanco issue @Folch

**Comment by xaviml** [comment]
Resulta que si mentres t'ataquen les aranyes es pausa el joc, les animacions no les fa, però la vida disminueix @Folch i pot arribar a sortir el game over. Torno a obrir la issue.

**Comment by JordiRQ** [comment]
El bug és per part dels NPCs. He pujat el fix a devel-B, repetiu els tests un cop devel-C i devel-B estiguin integrats en devel, sisplau.

**Comment by xaviml** [comment]
D'acord @JordiRQ, aquesta tarda-nit integrem i et donaré un feedback

**Comment by xaviml** [comment]
Tot solucionat en la integració @JordiRQ i @Folch. Tanco issue.
