### ISSUE TITLE
Asignar ubicaciones en el escenario para las arañas 

### ISSUE THREAD

**Issue by CristhianCarmona** [eloipuertas/ES2014B#129]
Desc : colocación de cubos en el escenario q luego serán reemplazados por las arañas. 

HE: 1h

CF: que cumplan con las ubicaciones de la wiki

**Comment by xaviml** [comment]
Para esto, ya hicimos un mapa en clase. Los del grupo devel-B ya han colocado las arañas. Ahora mismo se encuentra ya en devel-C @cctGitHub Cierro issue.

**Comment by CristhianCarmona** [comment]
@xaviml perfect
