### ISSUE TITLE
Create arm animation on Dummy char 

### ISSUE THREAD

**Issue by Payetus** [eloipuertas/ES2014B#13]
Creating an animation on dummy char.
On a humanoid(Subject to change) object create a 90 degree shoulder rotation, leaving the right arm perpendicular to the body.
Depends on issue #12 

Estimated time: 2.5 hours

**Comment by Payetus** [comment]
This issue is is part of issue #14

**Comment by pherrusa7** [comment]
@Payetus No pots tancar-te les issues, només ho pot fer l'integrador del teu grup, que sóc jo.
@Payetus D'aquesta issue jo no he vist res encara, per tant, queda oberta.
