### ISSUE TITLE
Programar que a l'atacar, el personatge principal es posi davant l'enemic

### ISSUE THREAD

**Issue by aniskhoury** [eloipuertas/ES2014B#148]
Actualment quan s'ataca a un enemic, ho fa des de la posició en la que està, sense tenir en consideració que poder està d'esquena a l'enemic.

Condició finalització:
Que l'atac sigui frontal.

**Comment by pherrusa7** [comment]
@aniskhoury Aquesta issue queda aplaçada pel següent sprint.

**Comment by aniskhoury** [comment]
Ok @pherrusa7  !

**Comment by pherrusa7** [comment]
@aniskhoury Et faltava la label grup-A

**Comment by pherrusa7** [comment]
@aniskhoury Funciona prou bé, pero s'hauría de donar algún retoc

**Comment by pherrusa7** [comment]
@aniskhoury Tanco issue, si cal retocar-la més obrim bug
