### ISSUE TITLE
#157 Check after adding the npc attributes (Issue #122): calculate/modify all the attributes correctly when is needed, so the npc works correctly

### ISSUE THREAD

**Issue by xavierfebrer** [eloipuertas/ES2014B#157]
Description:
- Recalculate the attributes/stats when needed. For example: when the spider throws a projectile, substract the correct amount of MP and recalculate the attributes/stats if needed.

Duration: 12h (some time may be shared with other issues because it englobes them too #122 )

Final condition:

The npcs attributes are modified correctly, when needed.

**Comment by Mithrandir0x** [comment]
Validated and integrated.
