### ISSUE TITLE
Create model and animations for a door

### ISSUE THREAD

**Issue by Mithrandir0x** [eloipuertas/ES2014B#158]
# Description

For each issue for `devel-B` branch, it is required to validate that the issue has been implemented correctly, and should be tested before deploying to `devel` branch.
## Done condition

A model of a door should be available in the assets view, with an animation controller that should be able to control the door's animations.

**Comment by Mithrandir0x** [comment]
The door should be placed where the red mark is indicated:

![portal_mark](https://cloud.githubusercontent.com/assets/204448/5141589/a38d9c72-7177-11e4-9ad8-985d90fde2a9.PNG)

![portal_mark_001](https://cloud.githubusercontent.com/assets/204448/5141601/d781323c-7177-11e4-83f4-2dbf4f53ee33.PNG)

**Comment by MCardus** [comment]
I will create the model and textures of this issue and @sbarrera  will animate it.
