### ISSUE TITLE
#170 Add all the images (white)

### ISSUE THREAD

**Issue by xavierfebrer** [eloipuertas/ES2014B#170]
Description:
Add all the images (white) to have all the files already, so that the programmer can assign them to the scenes without waiting the designer to finish them. After uploading the images, the designer can reupload them when he/she finishes them.
This issue is the first to be completed before: 161,162,163,169
Time left:
2h
Final condition:
Have all the images (files) ready for the programmer, without the need to have them finished.

**Comment by xaviml** [comment]
Bona feina @xavierfebrer, tanco issue
