### ISSUE TITLE
IndexOutOfRangeException

### ISSUE THREAD

**Issue by xaviml** [eloipuertas/ES2014B#172]
#### Como he encontrado este error

Este error se produce cuando cualquier aranya intenta pasar por la zona que he dejado marcada en la imagen de abajo.

![buges](https://cloud.githubusercontent.com/assets/3974003/5153824/08be912c-723c-11e4-91eb-190b108b18ee.PNG)
#### Soluciones que he probrado

He intentado quitar muros para que este espacio sea más grande, pero sigue dando el mismo error
#### Error

```
IndexOutOfRangeException: Array index is out of range.
SpiderAI.Update () (at Assets/spider/scripts/SpiderAI.cs:123)
```

``` cs
if ( target != null ) {
            if (myState.isAlive()){
                ...
                if (dist<attackRange){
                    if (currentAction==MOVING){
                        ...
                    }
                }else if (dist<aggroRange){
                    if (currentAction == PASSIVE){
                        ...
                    }else if (currentAction == ATTACKING){
                        ...
                    }else{
line 123 >>            if (Vector3.Equals(path.corners[current_corner],transform.position)){
                            current_corner++;
                        }
                        Vector3 dest = path.corners[current_corner];
                        myState.setDestination (dest.x, dest.y, dest.z);
                    }
                }
            }else if (currentAction == MOVING){
                ...
            }
        }
```

*Testeado sobre `devel`

**Comment by JordiRQ** [comment]
Això té pinta de ser problema de parametrització (attack range massa baix). Bàsicament, està a suficient rang com perquè el pathfinding consideri que ja estàs a sobre del destí, però no està entrant a la condició d'atac com hauria. Pujant el valor d'Attack Range de la SpiderAI s'hauria de solucionar

**Comment by Mithrandir0x** [comment]
I'm not entirely sure, but I believe it's a problem that a recalculation of the path happens and when that happens, the `current_corner` variable is updated to begin from the second element of `path.corners` array.

That array does not contain enough corner points to make a comparison.

The next commit will solve this issue, so I'm closing it.
