### ISSUE TITLE
Crear teranyines per decoració

### ISSUE THREAD

**Issue by MCardus** [eloipuertas/ES2014B#174]
Condició de finalització: Crear una teranyina per ambiental l'escenari.
Temps estimat: 1h

**Comment by xaviml** [comment]
@MCardus té la etiqueta 'Grup C' per algún motiu?

**Comment by MCardus** [comment]
Perque es un element decoratiu propi del terreny, grup C.

**Comment by xaviml** [comment]
Val, perfecte @MCardus, gràcies.
