### ISSUE TITLE
Fallo de animación al andar

### ISSUE THREAD

**Issue by xaviml** [eloipuertas/ES2014B#175]
#### Como he encontrado este error

Si mientras se está ejecutando la animación de atacar, se hace un click para andar, la animación de andar no se reproduce.

*Testeado sobre `devel`

**Comment by pherrusa7** [comment]
@Demenus Hauries d'ajudar al @aniskhoury  pel tema de l'animació.

**Comment by xaviml** [comment]
Bug fixed. Tanco issue @aniskhoury
