### ISSUE TITLE
Animació i só de caminar

### ISSUE THREAD

**Issue by pherrusa7** [eloipuertas/ES2014B#177]
#### Descripció:

Quan fem que el PJ camini clicant a un objecte o un mur del joc, quan arriba al límit l'animació de caminar i el so corresponent, no deixen de reproduir-se.

![animacioiso](https://cloud.githubusercontent.com/assets/8740816/5187781/c9a77616-74cf-11e4-9bfe-6b303f55456e.PNG)
#### Possible solució:

 Que l'animació i el so deixin de reproduir-se.

**Comment by pherrusa7** [comment]
@aniskhoury Per aquest bug crec que el que vas dir de posar un tag als murs i objectes és suficient per arreglar això. Anem parlant.

**Comment by pherrusa7** [comment]
@xaviml Pel tema del só, suposo que serveix la mateixa solució, no?

**Comment by xaviml** [comment]
Si, exacte. Ja li vaig comentar a @aniskhoury. si no s'en surt amb el so, li ajudaré.

**Comment by pherrusa7** [comment]
@xaviml @aniskhoury En els tests a devel-A amb els murs s'ha solucionat, pero quan hi ha una aranya morta i vols "pasar per sobre" l'animació i el só es continuen reproduint i el personatje no es mou.

**Comment by xaviml** [comment]
Tot perfecte, ja es pot tancar issue @pherrusa7 i @aniskhoury

**Comment by pherrusa7** [comment]
@aniskhoury @xaviml Yes! Bona feina
