### ISSUE TITLE
Poció

### ISSUE THREAD

**Issue by pherrusa7** [eloipuertas/ES2014B#178]
Si el PJ té la vida sencera, hauríem de fer que no pugui agafar la poció?

**Comment by xaviml** [comment]
Bona idea. @aniskhoury, apunta-t'ho per al següent sprint, si al Product Owner (@eloipuertas) li sembla bona idea.

**Comment by aniskhoury** [comment]
Ok @xaviml  @pherrusa7 ! Podriem comentar-li també si vol algun so (tant quan agafa una poció com quan no l'agafa perquè disposa de full HP), com ho veieu?

**Comment by xaviml** [comment]
Si, bona idea. Que et sembla @voriol?

**Comment by pherrusa7** [comment]
Ben fet @aniskhoury !
