### ISSUE TITLE
So mentre perds vida

### ISSUE THREAD

**Issue by pherrusa7** [eloipuertas/ES2014B#179]
Com existeixen punts morts on no veiem el personatge clarament, poden haver-hi aranyes que ens ataquen i no adonar-nos.

Crec que podríem afegir un so al PJ quan és atacat, alguna cosa més suau que quan mor.

**Comment by xaviml** [comment]
El PJ no té so quan es atacat, però l'aranya reprodueix un so quan ataca (#51). Tot i així sería una millora possar un so al personatge quan rep mal.

**Comment by pherrusa7** [comment]
@xaviml Si afegim aquesta issue, a algú del teu grup hauría de ser-li assignada.

**Comment by xaviml** [comment]
@voriol, que et sembla? 
To i així, ara s'està solucionant el problema del terreny, per  a que el personatge sempre sigui visible @pherrusa7

**Comment by voriol** [comment]
@xavi busco so i creo funcio per a quan ataquen al PJ.

**Comment by pherrusa7** [comment]
@xaviml Ok! 
@voriol Perfecte! :)

**Comment by voriol** [comment]
@pherrusa7 @xaviml @aniskhoury 

he afegit el so i les funcions que m heu demanat,

he fet la seguent actualització a la documentació de la WIKI so PJ:

`PJAudio.PlayGirlHurt;`
- so utilitzat per a quan un PJ femeni reb mal

`PJAudio.PlayManHurt;`
- so utilitzat per a quan un PJ masculi reb mal

**Comment by xaviml** [comment]
Perfecte @voriol, ja ho he testejat i integrat. He canviat tot a una funció que es diu: PJAudio.PlayHurt(), dintre controla si és el player1 o el 2. Ara actualitzo la wiki. Tanco issue.
