### ISSUE TITLE
Creation of an attack animation

### ISSUE THREAD

**Issue by Demenus** [eloipuertas/ES2014B#183]
Creation in blender of an attack animation

Estimation: 1h

Ends when: The knight blades his sword

**Comment by pherrusa7** [comment]
@Demenus Aquesta issue queda ajornada pel següent sprint.

**Comment by pherrusa7** [comment]
@Demenus La faràs tal que utilitzin l'arma no?

**Comment by pherrusa7** [comment]
@Demenus Bona atac amb l'espasa!
