### ISSUE TITLE
Change the body to body attack animation so it hits the spider

### ISSUE THREAD

**Issue by Payetus** [eloipuertas/ES2014B#184]
## Description

Changes  the body to body attack animation for the female Main Character.  Right now the body to body attack animation hits the air because the spider is to small, so we should change the animation so that the main characters fist hits lower.
## Objectives

Refactor the body to body attack animation for the female Main Character
## Subtasks
- [x] Refactor body to body attack animation on female MainCharacter model 8h
## TestCase
- When getting hit by a spider the animation should be played.
## Estimated Time

Estimated time: 6 hours
## ProductBacklog

El pèrsonatge ataca cos a cos.

**Comment by pherrusa7** [comment]
@Payetus Falten descripcions! Sense descripcions la issue queda invàlida i sense milestone.

**Comment by pherrusa7** [comment]
@Payetus Tanco issue. Ja està fet.
