### ISSUE TITLE
Create an animation for the MainCharacter of being hit by a npc spider attack.

### ISSUE THREAD

**Issue by Payetus** [eloipuertas/ES2014B#185]
## Description

Creates a "Being hit" animation for the female Main Character. When the main Characters recieves damage or gets hit by the spider this animation will be played. The animation will consist of the character leaning backwards in a sudden and jerky movement.
## Objectives

Create a "Being hit" animation on female MainCharacter.
## Subtasks
- [x] Create a  "Being hit" animation on female MainCharacter model 8h
- [ ] Adding a new state associated with animation to the animation controller.
## TestCase
- When getting hit by a spider the animation should be played.
## Estimated Time

Estimated time: 8 hours
## ProductBacklog

Personatje reb mal.

**Comment by pherrusa7** [comment]
@Payetus Falten descripcions! Sense descripcions la issue queda invàlida i sense milestone.

**Comment by pherrusa7** [comment]
@Payetus Tanco issue. Ja no es farà.
