### ISSUE TITLE
#195 Add animated healthmanabars over the npcs, add the border damage image

### ISSUE THREAD

**Issue by xavierfebrer** [eloipuertas/ES2014B#195]
Description:
Change the static textures from the healthmanabars of the npcs to animations

Time left:
8h

Final Condition:
The textures from the healthmanabars of the npcs are animations now

**Comment by xavierfebrer** [comment]
NOTA IMPORTANT!
Està posat a Project/design/textures PER DEVEL-C
Està posat a dins de spider/... PER DEVEL-B

**Comment by xaviml** [comment]
Cap problema @xavierfebrer. Ja ho he vist, però et tancaré la issue quan ho vegi en devel millor.
