### ISSUE TITLE
#196 Add terrain textures to change the look and feel of the terrain

### ISSUE THREAD

**Issue by xavierfebrer** [eloipuertas/ES2014B#196]
Description:
Create new textures for the terrain

Time left:
8h

Final Condition:
The terrain has new textures, ready to be applied.

**Comment by xavierfebrer** [comment]
The textures are inside:

ES2014B\Project\design\Assets\Textures\terrain textures look and feel

**Comment by xaviml** [comment]
He vist les textures en la carpeta dessign. Les haurem de colocar al joc. Tanco issue @xavierfebrer
