### ISSUE TITLE
Millorar càmera

### ISSUE THREAD

**Issue by Folch** [eloipuertas/ES2014B#197]
La càmera actualment quan no veu al personatge principal pels murs fa que siguin transparents si s'executa des de Unity pero no en el build. S'ha de corregir això i millorar la transparència si dóna temps. En cas que no es pugui arreglar que no es vegi transparent en el build es deixarà sense renderitzar.

Hores estimades: 10h

Condició de finalització:
- O murs transparents en el build
- O murs no renderitzats

(Preferentment la primera)
- Els 'chaflanes' que són columnes formades per vàries pedres s'han de veure transparents.
- La transparència ha de funcionar a un cert marge, ja que fins ara només funciona només quan el personatge toca el mur o es aprop del seu centre.
- Zoom en sentit correcte; cap endavant augmenta, cap endarrere disminueix.
- S'ha de limitar el zoom per a que no es vegi per sobre dels murs ni columnes i doni una sensació d'immersió major.
- El zoom ha de ser més ràpid.

**Comment by xaviml** [comment]
Perfecte @Folch. Faltaria possar que s'ha limitat també el zoom de la càmera. Tanco issue.

**Comment by Folch** [comment]
Ui @xaviml es veritat, modifico la condició de finalització ara mateix!
