### ISSUE TITLE
Crear escenario final juego 

### ISSUE THREAD

**Issue by CristhianCarmona** [eloipuertas/ES2014B#198]
Desc: creación de escenario final del juego que será accesible después de haber matado las arañas 

TE: 4h

CF: accesible desde el nivel anterior

**Comment by Mithrandir0x** [comment]
Tengo esta duda: ¿el nuevo escenario que hay en `devel-C` es para tener el desarrollo de la escena por separado, y una vez lo tengáis, será integrado a PlayScene? o, ¿es un nivel nuevo y los del grupo b vamos a tener que hacer cambios sobre la lógica de `Gameflow.cs` para adaptarnos a los cambios?

@JordiRQ seguirá implementando la lógica del juego en base a que sólo habrá una única escena, y no deberá hacer ninguna lógica nueva para una segunda escena.

Además, no tendría sentido alguno tener una puerta detrás de la araña gigante, porque si vamos a tener que pasar por él en plan "portal-wow-instancia", pues no tiene mucha gracia, y creo que de esto no se dijo nada el miércoles pasado.

**Comment by CristhianCarmona** [comment]
@Mithrandir0x no tengas más dudas, el nuevo escenario ahora está en una misma escena. 
De todas maneras esto xavi ayer lo preguntó por el grupo del WhatsApp y nadie dijo nada, ante eso pues seguí adelante.

**Comment by xaviml** [comment]
Perfecto, cierro issue @cctGitHub
