### ISSUE TITLE
Change projectile being shoot by the Spider into the web implemented on #164

### ISSUE THREAD

**Issue by JordiRQ** [eloipuertas/ES2014B#203]
The Spider has to shoot the object that's been modelled.

Final condition:
Add prefab for the web object. 
Have the spider throw this projectile instead of a sphere.
Estimated time: 1h

**Comment by Mithrandir0x** [comment]
When integrating into devel, I've found that the projectiles is not thrown at the correct rotation angle. And it's not visible, though the spider has thrown a spider web as it consumes mana.

Use the PlayScene to check if the prefab is being instanced correctly. Forget about using NpcNavmeshScene for now.
