### ISSUE TITLE
When the camera is zoomed out, it is not possible to attack a spider

### ISSUE THREAD

**Issue by Mithrandir0x** [eloipuertas/ES2014B#206]
When the camera is far away from the character, and the player tries to attack a spider, the character won't attack the spider.

I believe this is an issue with line 102 from `MainPJMovement.cs`:

```
if (Physics.Raycast (Camera.main.ScreenPointToRay (Input.mousePosition), out hit, 1000.0f, ~(1 << 8))) {
```

As you can see, the distance of the ray (1000.0f) may not be enough from that distance.

**Comment by xaviml** [comment]
Bug fixed, the new line is:
`Physics.Raycast (ray, out hit, float.PositiveInfinity, ~(1 << 8))`
