### ISSUE TITLE
IA bug

### ISSUE THREAD

**Issue by xaviml** [eloipuertas/ES2014B#210]
Cuando matas a las 6 arañas y aparecen otras 5, estas 5 no persiguen al personaje y se dirigen hacia el sud del terreno.

**Comment by xaviml** [comment]
Deixo la issue tal com estava, però amb la etiqueta de duplicada. Quan es realitzi, tanquem aquesta issue també @JordiRQ y @Mithrandir0x

**Comment by Mithrandir0x** [comment]
Purge the unclean, burn the heretic, and set duplicated issues on fire!
