### ISSUE TITLE
Crear més elements sala fi del joc

### ISSUE THREAD

**Issue by MCardus** [eloipuertas/ES2014B#217]
Crear una montanya de monedes d'or i un cofre per la sala de fi de joc.
Temps estimat: 2h

**Comment by Mithrandir0x** [comment]
Which elements? I'm the man who draws a fucking owl like a fucking boss:

![radsf](https://cloud.githubusercontent.com/assets/204448/5367476/4a59c390-7ffc-11e4-9a82-eafcc558477c.jpg)

But I cannot guess which objects you wanted to create.
