### ISSUE TITLE
#220 Add easy, normal, hard difficulty textures with background

### ISSUE THREAD

**Issue by xavierfebrer** [eloipuertas/ES2014B#220]
Description:
Add new textures for the easy, normal, hard and its background texture

Time left:
5h

Final Condition:
The menu to choose difficulty must show easy, normal, hard and the background.

**Comment by Mithrandir0x** [comment]
We're really going to support three levels of dificulty?

**Comment by xaviml** [comment]
Perfecte @xavierfebrer, tot perfecte. Tanco issue.
