### ISSUE TITLE
#221 Create a background for the pause menu and the gameover menu

### ISSUE THREAD

**Issue by xavierfebrer** [eloipuertas/ES2014B#221]
Description:
Create 2 background textures for the menu of pause and gameplay

Time left:
4h

Final Condition:
The pause and the continue menu have a background

**Comment by xavierfebrer** [comment]
The textures are inside:

ES2014B\Project\design\Assets\Textures\pause_gameover_background

**Comment by xaviml** [comment]
Perfecte. Tanco issue @xavierfebrer
