### ISSUE TITLE
Poder atacar magia més freqüentment

### ISSUE THREAD

**Issue by xaviml** [eloipuertas/ES2014B#222]
En comptes que gasti tot el maná, que gasti només 1/3 del MAXHP

**Comment by aniskhoury** [comment]
Okis @xaviml  ! Mmm, enllaçant amb la issue #225 que en penses que segons el nivell de la dificultat es canvii aquest valor?  Per altre banda, per confirmar, el mana gastat és 1/3 del màx. de Vida?

**Comment by aniskhoury** [comment]
He posat que el mana gastat sigui el següent:
NivellDificultat pot ser 1,2,3 on 1 és el Easy, 2 el Medium i 3 el Hard
Utilitzar la màgia costa NivellDificultat/maxVidaPersonatje parts de la vida màxima
Que en penseu? En tot cas, he deixat tot això parametritzat perque canviar-ho sigui molt fàcil, lo que podem fer és jugar una mica i veure els diferents nivells de dificultat i si costa massa anar canviant els pesos. Suposo que tot plegat dependrà de la vida de les aranyes, nombre de pocions, etc... 
Si alguna persona vol que ho canvii que sàpiga que ho puc canviar en un moment!

**Comment by xaviml** [comment]
Rectifica, si m'equivoco: 
En cas que la vida màxima fos: 500, la magia costaria:
- **Easy:** 1/500 = 0.002
- **Medium:** 2/500 = 0.004
- **Hard:** 3/500 = 0.006

No creus que es massa petit? És més, que te a veure el MaxVidaPersonatge amb la magia? 

**Proposta**
Si es vol canviar aquest paràmetre depenent de la dificultat, seria més lògic fer el següent: `(lvl/hard) * MaxManaPersonatge`. Llavors seria (en cas que el max mana fos: 100):
- **Easy:** 1/3 \* 100 = 33.33
- **Medium:** 2/3 \* 100 = 66.66
- **Hard:** 3/3 \* 100 = 100

Tot i així jo faria que sempre fos fixe, fent 1/3 per exemple.

**Comment by pherrusa7** [comment]
@xaviml @aniskhoury Jo ho deixaria fixe. Demà quan estigui tot integrat juguem amb els paràmetres.

**Comment by xaviml** [comment]
Hem possat que gasti un 25% del MPMax. Tanco issue
