### ISSUE TITLE
Rang de magia massa curt

### ISSUE THREAD

**Issue by xaviml** [eloipuertas/ES2014B#224]
La distancia d'atac de magia, estaria bé que fos més gran, ja que t'has d'apropar massa per fer magia.

**Comment by aniskhoury** [comment]
D'acord, a quants metres aniria bé més o menys? a 120 metres sembla prou raonable per un joc d'estrategia, que en penses?

**Comment by xaviml** [comment]
Suposo que perfecte, quan estigui tot a devel, tancarem aquest bug. Lo important és deixar-ho en una variable per canviar-ho amb facilitat @aniskhoury

**Comment by xaviml** [comment]
Perfecte, ja es pot tancar la issue @aniskhoury
