### ISSUE TITLE
Millora del hud

### ISSUE THREAD

**Issue by Folch** [eloipuertas/ES2014B#226]
Fins ara els menús de pausa i game over no tenien fons, li col·locaré jo el fons que em passi @xavierfebrer i es posarà un fons vermell depenent de la vida del personatge. També es posarà un botó al game over i al menú de pausa de 'Restart' per tornar a començar.

5 hores estimades

Condició de finalització:
- [x] Les opcions del menú de pausa tenen un fons
- [x] Les opcions del menú de game over tenen un fons
- [x] Col·locar 'Restart' al game over i al menú pausa.
- [x] Programar el Restart
- [x] Fons vermell a tot el hud de sang que faci com 'pampallugues' quan la vida del personatge principal es baixa

**Comment by xaviml** [comment]
Perfecte, tot correcte @Folch. Tanco issue
