### ISSUE TITLE
Mejorar visibilidad de acceso discreto en nivel principal

### ISSUE THREAD

**Issue by CristhianCarmona** [eloipuertas/ES2014B#228]
Desc: colocar antorcha que se apague de forma intermitente, además de rastros en el suelo que faciliten su visibilidad por el jugador
TE: 3h
CF: conseguir que el acceso sea visible facilmente por el jugador

**Comment by xaviml** [comment]
Perfecto, ahora el pasillo se consigue ver mucho mejor. Cierro issue @cctGitHub
