### ISSUE TITLE
New attack animation for the big spider 

### ISSUE THREAD

**Issue by sbarrera** [eloipuertas/ES2014B#229]
The big  spider should  do an attack that looks scarier and make the difference with the others spiders.
The animation should show the spider attacking.

Estimated time effort: 2 hours
- [ ] The animation is tested and working in unity

**Comment by Mithrandir0x** [comment]
The animation is done, but it has not been integrated in the project. This issue will robertcopped.

![1417871449978](https://cloud.githubusercontent.com/assets/204448/5368107/3b2b5ed2-8002-11e4-8b52-839ccaa065a0.jpg)
