### ISSUE TITLE
Creation of a magic animation for amazon and knight

### ISSUE THREAD

**Issue by Demenus** [eloipuertas/ES2014B#231]
Creation in blender of two magic attacks animation

Estimation: 2h

Ends when: The amazona and the knights moves their hands to throw a magic attack

**Comment by pherrusa7** [comment]
@Demenus Veig que puja el braç pero no surt cap animació

**Comment by pherrusa7** [comment]
@Demenus Està ok, la bola de foc la feia el grup C
