### ISSUE TITLE
C-237-so you win

### ISSUE THREAD

**Issue by voriol** [eloipuertas/ES2014B#237]
Descripcio: so per a quan es guanya la partica

Condicio finalitzacio: canviar la musica de ambient quan es guanya la partida, el so ha de ser del tipus "victoria"

Temps estimat: 2h

**Comment by xaviml** [comment]
Com l'estat de 'win' no està fins la integració de l'ogre, quan integrem l'ogre et tancaré la issue, però ja he vist que està el so en Assets. He lincat el so a la càmera.

**Comment by xaviml** [comment]
Ja està integrat, però hem possat la música dels crédits com la música guanyadora @voriol. Tanco issue
