### ISSUE TITLE
C-238-so ogre

### ISSUE THREAD

**Issue by voriol** [eloipuertas/ES2014B#238]
Descripcio: Afegir a la llibreria PNJ sons per al ogre

Condició de finalització: 
- so al atacar
- so al rebre mal
- so al morir

Temps estimat: 2h

**Comment by xaviml** [comment]
Igual que la issue #237, quan l'ogre estigui integrat, tancaré la issue, però ja he vist els sons a la carpeta 'Troll>sounds'. Sonen perfecte! @voriol

**Comment by xaviml** [comment]
L'ogre ja té els sons incorporats, perfecte. Tanco issue @voriol
