### ISSUE TITLE
Threading bug

### ISSUE THREAD

**Issue by xaviml** [eloipuertas/ES2014B#240]
## Bug

A vegades el player fa la animació de morir i pot seguir caminant (tot i que esigui en el terra)
## Introducció

Possem el cas dels següents threads que executen aquestes parts de funció:
**MainPJMovement.cs** - Thread-1

``` cs
public override void onAttackReceived(int dmg){
    ...
    if (this.getHP () <= 0) {
        //Application.LoadLevel();
        PJAudio.PlayKilled ();
        anim.SetBool ("Die", true);             
    } else {
        ...
    }
}
```

**HUD.cs** - Thread-2

``` cs
if (!pj.isAlive()) {
    // Actualitzar HUD i mostrar gameover
        ....
}
```

**RegenetarionPJ.cs** - Thread-3

``` cs
void Update () {
    if (this.time > 0){
        this.time -= Time.deltaTime;
    }else{
        this.time = 1.0f;
        pj.increaseHeal(this.regenHP);
        pj.increaseMana(this.regenMP);
    }
}
```
## Explicació

Fins ara lo normal, és que s'executi **Thread-1** (que fa l'animació de morir i el so) y després **Thread-2** (Mostra en le HUD el gameover, perquè veu que la vida del pj és <=0).

Però que passa si entre **Thread-1** i **Thread-2** s'executa **Thread-3**? Passaria el següent:
- **Thread-1** faria la animació i el so de la mort.
- **Thread-3** regeneraria vida i faria que la vida fos major que 0.
- **Thread-2** veuria que la vida es major o igual que 0 i no mostraria pas el GameOver.
## Solució

Si no m'equivoco es tan fàcil com possar abans de la regeneració de vida del pj:
`if(pj.isAlive())`
Això el que farà es que només recuperarà vida si el personatge està viu, si està mor, no ho farà.

**Comment by aniskhoury** [comment]
@xaviml Bona troballa de bug! Ho he implementat i sembla que funciona (però ja saps com són els fils...), en tot cas, ara el que puc garantir es que no augmentarà la vida del Pj si està mort (que com a mínim, era un bug). He anat provant i no he vist que passes més això.

**Comment by xaviml** [comment]
Perfecte @aniskhoury, aquesta issue, la donarem per tancada quan ho haguem provat uns quants cops.

**Comment by pherrusa7** [comment]
@xaviml @aniskhoury Un cop tastejada a devel veiem si em resolt bé el problema

**Comment by xaviml** [comment]
Perfecte, ja s'ha testejat força. Tanco issue @aniskhoury i @pherrusa7
