### ISSUE TITLE
Moure el Pj Principal mentres es prem el botó esquerra del mouse

### ISSUE THREAD

**Issue by aniskhoury** [eloipuertas/ES2014B#241]
Quan l'usuari premi el botó esquerra del mouse, el Pj Principal hauria d'anar-se desplaçant en la direcció seleccionada per l'usuari.

Aquesta issue finalitzarà quan el Pj Principal es vagi desplaçant a on l'indiqui l'usuari fins que deixi de premer el botó esquerra del mouse

De hores... 0 hores xD, aprox. uns 10-15 minuts.

**Comment by pherrusa7** [comment]
Bona feina @aniskhoury Tal i com volia el project owner!
