### ISSUE TITLE
Camera: Enfocar teranyina quan desapareix

### ISSUE THREAD

**Issue by Folch** [eloipuertas/ES2014B#247]
Quan desapareix la teranyina no hi ha un feedback al usuari conforme pot avançar. 

2 hores estimades

Condició de finalització:
- Que la càmera enfoqui a la teranyina just quan desaparegui

**Comment by Folch** [comment]
@xaviml  issue acabada i integrada

**Comment by xaviml** [comment]
Perfecte @Folch. Tanco issue
