### ISSUE TITLE
Història dels personatges

### ISSUE THREAD

**Issue by pherrusa7** [eloipuertas/ES2014B#253]
## Descripció

Narrar les històries completes dels personatges principals
## Temps estimat

8 hores
## Objectius
- [x]  Descriure una història per Za’Atha, la nostra maga.
- [x] Descriure una història per Gargarath, el nostre guerrer.

**Comment by pherrusa7** [comment]
## ZA’ATHA

power: ***\* force: *\*   mana: ***\*  magic: *****

Daughter of Zatho, wizard,  and the chemistry ATHARE, ZA’ATHA heredity the best part of both. Within her early age, 55 (wizards use to live above 300 human years), she is able to invoke the most powerful enchantments to destroy the stronger warriors. 

Besides, she prepares her own  potions to cure and heal sick humans. Also, she could get confuse the wisest man as well, or bring the true from liars.  

In our adventure, ZA’ATHA needs to get into the deepest catacombs - where an old mummy had been buried few years ago-  having to overcome all kind of creatures which she had never fight before. Her only  goal is to get an appreciate elements for her potions- which the legend said it could be founded into the mummy sepulcher. 

However, she could not fight using her witchcraft with those creatures since they are unaffected from magic, so she is not strong enough to give hand to hand combat.  

With this in mind, she will be joined by GARGARATH, an eternal life convicted warrior, whom needs the magic and the same elements to end the curse.

**Comment by pherrusa7** [comment]
## GARGARATH

power: ****\*    force: ****\*    mana: *\*    magic: *

Much more before from the Samuray time, in Honshu (本州), main Island from the Japanese archipelago, an old dynasty of warriors look after the people safety, the Rathingers. Among them it was a young knight, GARGARATH. 

He had not enough watching after his people, and his gain of power was growing inordinately, that he wanted to find unknown places to fight to darkest powers, underworld beasts and a lot of other kind of detestable creatures. 

In one of those fights, Devil said to him that if he could kill him, he would be eternal.  Such as he adverts him, GARGARATH had stayed cursed forever and ever. 

Two thousand years after, our main character shares our adventure with ZA’ATHA to the depths of the catacombs to get with the spell that release him from the curse.

**Comment by xaviml** [comment]
Perfect, this is the story about the game:

"Za'atha and gargarath looking for something that is hidden in a deep dungeon.
They do not know the surprises and traps behind this dungeon, both are about to experience it.
Za'atha and Gargarath have a long history that unites them."

Now, @aniskhoury is about to finish the website, and he'll set these stories.
