### ISSUE TITLE
Crear index.html i treballar amb la pàgina web

### ISSUE THREAD

**Issue by MCardus** [eloipuertas/ES2014B#254]
Crear pàgina inicial pàgina web. 

Condicions de finalització:

-Ha d'apareixer el trailer
-Ha d'apareixer un mode de financiació tipus kick starter
-Ha d'haver-hi una petita galeria del joc
-Ha d'haver un petit text a mode d'introducció al joc.
-L'estètica de la web ha de ser coherent amb la de joc.
-Ha d'haver un petit menu per poder navegar per la pàgina web.

Treballar amb altres pàgines de la web.

-Ajudar a fer la resta de pàgines a nivell de disseny i implementació.

**Comment by xaviml** [comment]
Ja podem tancar aquesta issue @MCardus.
