### ISSUE TITLE
Create HUD lifebar

### ISSUE THREAD

**Issue by Roka0006** [eloipuertas/ES2014B#26]
E.T: 20 min

Final condition: See a sphere with red material.

**Comment by xaviml** [comment]
Tant el lifebar (#26) i el manabar (#27), han d'aparèixer com a HUD en la escena de joc, no en la escena de selecció de personatge. @Roka0006

**Comment by xaviml** [comment]
Mirar la issue #7, allà està explicat perquè està oberta aquesta tasca. @Roka0006

**Comment by xaviml** [comment]
Perfecte, veig una esfera de color vermell. Tanco issue @Roka0006
