### ISSUE TITLE
so al caminar personatge principal

### ISSUE THREAD

**Issue by voriol** [eloipuertas/ES2014B#3]
- Descripció: Reproduir so quan el personatge principal es desplaci
- Condició Finalització: S'ha de reproduir un só que emuli una passa cada cop que el personatge es desplaci
- Temps estimat: 4h

**Comment by xaviml** [comment]
Bona feina @voriol, tanco la issue.

**Comment by xaviml** [comment]
Com hem tingut problemes amb les passes, necessitem que possis les passes en la llibrería de so. @voriol

**Comment by xaviml** [comment]
Perfecte. He hagut de canviar un par de cosetes al script per a que el so sigui continu però, el que ja t'he comentat @voriol
