### ISSUE TITLE
Bug Incompatibility Blender Model with Mecanim [Unity] Animation

### ISSUE THREAD

**Issue by Payetus** [eloipuertas/ES2014B#39]
## Description

There is an issue trying to attach the the Unity Animation to the model imported from Blender.

Need help of Modeler @Demenus 
#### Problem

First Problem encountered Body does not have a Rgigging.

![2014-10-14_1034](https://cloud.githubusercontent.com/assets/3797659/4647892/589476fc-547e-11e4-902a-dffe90caaa6b.png)
#### Solution

Bone Structure included in blender then imported to Unity
#### Problem

The actual humanoid body structure of blender is incompatible with Unity.

![2014-10-14_1230](https://cloud.githubusercontent.com/assets/3797659/4647962/ceda145c-547e-11e4-8cb1-41957d99ce9a.png)
#### Possible Solution
1. Create blender model and atach skeleton using the free addon of blender Rigify
2. Create Animation on blender model then import into unity

**Comment by pherrusa7** [comment]
@Payetus Descrius un problema, però has de descriure una tasca a fer en aquesta issue i una condició d'acabament.

**Comment by pherrusa7** [comment]
@Payetus Et falta crear la issue per l'animació de l'atac del personatge principal

**Comment by Payetus** [comment]
Issue Fixed 
![2014-10-29_1813](https://cloud.githubusercontent.com/assets/3797659/4830599/eb950ae6-5f8e-11e4-9661-0047db0e013e.png)
