### ISSUE TITLE
QA: Integrar personatge principal

### ISSUE THREAD

**Issue by pherrusa7** [eloipuertas/ES2014B#4]
## Descripció

Integrar el disseny, l'animació i la programació del personatge principal a aquesta primera versió del terreny de joc i dels NPC's.
## Temps estimat

8 hores

**Comment by xaviml** [comment]
@pherrusa7  aquesta issue ja es pot tancar.

**Comment by pherrusa7** [comment]
@xaviml Aquesta issue no la vaig fer desglossada i per tant, fins que no integri l'animació, no l'hauria de tancar.
