### ISSUE TITLE
Reprogramar menu per reintegració sprint 1

### ISSUE THREAD

**Issue by Folch** [eloipuertas/ES2014B#40]
Per arreglar els errors del sprint 1, en aquest sprint 2 l'artista del menú fara un nou disseny del menú amb el qual s'ha de reprogramar.

5 hores estimades

Condició de finalització: que al donar al quit se surti del menu principal (on hi ha new game i quit game, explicats pel dissenyador) -moure d'una escena a l'altre-, que al donar al new game vagi a una nova escena on puguem escollir un dels 3 personatges principals i que al donar-li al play de sota del personatge que vulguem per jugar es carregui en el mapa

**Comment by xaviml** [comment]
@Roka0006, fixat en la condició de finalització, les condicions de finalització han de ser així.

**Comment by xaviml** [comment]
Bona feina. Tanco issue @Folch
