### ISSUE TITLE
Re-crear terreno del sprint 1

### ISSUE THREAD

**Issue by CristhianCarmona** [eloipuertas/ES2014B#47]
Descripción: volver a crear el terreno del sprint 1. El nuevo terreno incluye: muros globales de la escena, habitáculo desde donde partirá el personaje principal, espacio para puerta y antorcha(fuego)
Dimensiones: 512x256x700

Horas estimadas: 9

Condición de finalización: que el personaje principal pueda moverse libremente respetando las retricciones naturales de los elementos que incluye el terreno.

**Comment by Folch** [comment]
*T'he afegit que aquesta issue és del sprint 2

**Comment by xaviml** [comment]
Perfecta descripción de finalización. Las dimensiones ponlas en la wiki, para saber sobre que dimenciones trabajamos. @cctGitHub

**Comment by xaviml** [comment]
Perfecto, cierro issue.
