### ISSUE TITLE
Programar  GameOver de dins de l'escena del joc

### ISSUE THREAD

**Issue by Folch** [eloipuertas/ES2014B#48]
Programar el gameOver de l'escena del joc per a que et surti l'avís de que se t'ha acabat la partida i tenir la possibilitat de tornar al menú principal

3h estimades

Condició de final: que al quedar-se el personatge principal sense vida surti un missatge de game over a l'escena del joc i un butó que et porti al menú principal

**Comment by xaviml** [comment]
GameOver es una escena diferent o és la escena del joc amb un missatge? @Folch

**Comment by Folch** [comment]
@xaviml això ho haig de parlar encara amb l'artista  , com tens pensat fer-ho @Roka0006 ?

**Comment by Folch** [comment]
Al final @xaviml  l'he programat a la mateixa escena ja que sinó em semblava una mica cutre

**Comment by xaviml** [comment]
Perfecte @Folch

**Comment by xaviml** [comment]
Si canvies aquesta issue, canvia el títol i la condició de finalització @Folch

**Comment by Folch** [comment]
Fet @xaviml

**Comment by xaviml** [comment]
Perfecte.
