### ISSUE TITLE
Tornar al mainMenu amb ESC

### ISSUE THREAD

**Issue by Folch** [eloipuertas/ES2014B#49]
Apretant 2 vegades seguides el botó ESC s'ha de tancar la partida i tornar al menú principal

US:  As a user I want to return main menu by pressing esc key two times.

5 h estimades

Condició de finalització: durant la escena del joc si apretem 2 vegades seguides (menys de 0.5 segons entre ESC i ESC) s'ha de tornar al main menu

**Comment by xaviml** [comment]
Perfecte funciona, tanco issue @Folch
