### ISSUE TITLE
C-50-so al atacar mele PJ

### ISSUE THREAD

**Issue by voriol** [eloipuertas/ES2014B#50]
Descripció: Reproduir so quan el personatge principal faci un atac cos a cos

Condició Finalització: S'ha de reproduir un só quan el personatge principal faci un atac cos a cos que resti vida al PNJ i un altre diferent quan faci un atac cos a cos però que no acerti al PNJ

Temps estimat: 4h

**Comment by xaviml** [comment]
Perfecte, bona feina @voriol. Tanco issue
