### ISSUE TITLE
C-51-so al atacar mele PNJ

### ISSUE THREAD

**Issue by voriol** [eloipuertas/ES2014B#51]
Descripció: Reproduir so quan el enemic faci un atac cos a cos

Condició Finalització: S'ha de reproduir un só quan el PNJ faci un atac cos a cos que resti vida al PJ i un altre diferent quan faci un atac cos a cos però que no acerti al PJ

Temps estimat: 4h

**Comment by xaviml** [comment]
Perfecte, bona feina @voriol. Tanco issue
