### ISSUE TITLE
C-52-iluminar catacumba

### ISSUE THREAD

**Issue by voriol** [eloipuertas/ES2014B#52]
Descripció: Iluminar la catacumba

Condició Finalització: Iluminar la catacumba fins a que tingui un aspecte semblant a,

![skullshot3](https://cloud.githubusercontent.com/assets/6683852/4689193/f34fce38-56ab-11e4-8e11-00d1d0360302.jpg)

Temps estimat: 4h

**Comment by xaviml** [comment]
Mira @Roka0006, com a condició final també pots posar una imatge o borrany, com ha fet @voriol

**Comment by xaviml** [comment]
Perfecte, bona feina @voriol. Tanco issue
