### ISSUE TITLE
C-53-so ambient catacumba

### ISSUE THREAD

**Issue by voriol** [eloipuertas/ES2014B#53]
Descripció: Reproduir un fil de so a la catacumba

Condició Finalització: S'ha de reproduir un só a la catacumba durant les escenes que no siguin de combat, s'ha de sentir el aigua que es filtra per les catacumbes ( en forma de gotes ), corrents de aire i petits animals com rat penats o aranyetes,

Temps estimat: 2h

**Comment by xaviml** [comment]
Perfecte, bona feina @voriol, dóna el pego la música de fons. Tanco issue
