### ISSUE TITLE
C-54-musica de combat en escenes de combat

### ISSUE THREAD

**Issue by voriol** [eloipuertas/ES2014B#54]
Descripció: Reproduir musica de combat en les escenes de combat

Condició Finalització: S'ha de reproduir musica de combat en les escenes de combat, ha de ser un fil musical motivador i animat, 

Temps estimat: 2h

**Comment by xaviml** [comment]
Tot i que potser es canvia el so, la llibreria per reproduir aquest so, ja hi és. Per tant, tanco issue. @voriol

**Comment by voriol** [comment]
reobro aquesta issue per a que es tingui en compte de cara a la implementació

durant el combat del ogre s ha de reproduir aquest so

**Comment by xaviml** [comment]
Perfecte @voriol, ho posso en la meva issue de testing

**Comment by xaviml** [comment]
@JordiRQ recorda de fer la crida pertinyent a aquest so d'ambient. 
https://github.com/eloipuertas/ES2014B/wiki/so%20ambient
`AmbientAudio.PlayFight();`

**Comment by JordiRQ** [comment]
Ja està fet, tranquil.
https://github.com/eloipuertas/ES2014B/blob/devel-B/Project/unity/Assets/Troll/Scripts/TrollAI.cs
de devel-B, línea 53

**Comment by xaviml** [comment]
Ja s'escolta la música, perfecte. Tanco issue.
