### ISSUE TITLE
Add the trigger that opens the door

### ISSUE THREAD

**Issue by JordiRQ** [eloipuertas/ES2014B#58]
Create an invisible object that activates a door's animation when the player character collides with it.

Final condition:
Add C# script
Add an invisible object with collider
Code implemented into the trigger's methods

**Comment by Folch** [comment]
(Corregeixo l'etiqueta del label C al label B)

**Comment by JordiRQ** [comment]
Reopening this issue since the door object has been changed and the animation controller needs some tweaking to adapt it to the door's animations
