### ISSUE TITLE
Programació menú principal

### ISSUE THREAD

**Issue by Folch** [eloipuertas/ES2014B#6]
Agafar les característiques del personatge principal escollides (en el menú principal) i que al donar-li al play es passin a l'escena on es jugarà

As a user I want to create my character by selecting its main attributes: Strength, Resistance, Magical Power and Agility

Condició de finalització: que les característiques seleccionades en el menú principal es guardin per poder saber quines s'han seleccionat en l'escena del joc. Poder també seleccionar una feature mitjançant el ratolí (fent click).

(8h estimades).

**Comment by xaviml** [comment]
Has de posar les hores estimades que et portarà aquesta issue @Folch.

**Comment by Folch** [comment]
Ui si despiste, merci per avisar!
