### ISSUE TITLE
 #65 Creación de columna y muro estilo medieval

### ISSUE THREAD

**Issue by CristhianCarmona** [eloipuertas/ES2014B#65]
Descripcion: diseñar y crear columna y muro de estilo medieval que sea capaz de facilitar el diseño del entorno del juego

Horas estimadas: 2

Condición de finalización: el objeto se podrá arrastrar y soltar en el escenario, con sus colliders pertinentes.

**Comment by CristhianCarmona** [comment]
que ha pasado con esta @xaviml ?

**Comment by xaviml** [comment]
Que ha pasado de que? @cctGitHub

**Comment by CristhianCarmona** [comment]
que se la has puesto a @JordiRQ que ya casi la termino

**Comment by xaviml** [comment]
Perdona.. Ha sido un error mío. Ya está.

**Comment by CristhianCarmona** [comment]
;)

**Comment by xaviml** [comment]
Perfecto, buen trabajo @cctGitHub. Cierro la issue.
