### ISSUE TITLE
#66 Creación de estructura estilo catacumba

### ISSUE THREAD

**Issue by CristhianCarmona** [eloipuertas/ES2014B#66]
Descripción: diseñar y crear estructura para el techo estilo catacumbas/medieval

Horas estimadas: 2

Condicion de finalización: el objeto -con sus colliders y texturas- se podrá manipular facilmente arrastrando y soltando.

**Comment by CristhianCarmona** [comment]
y con esta otra tamb @xaviml ¿?

**Comment by xaviml** [comment]
Perfecto, buen trabajo @cctGitHub. Ahora da el pego a una catacumba. Cierro la issue.
