### ISSUE TITLE
#69 construcción escenario lucha entre PP y NPC's

### ISSUE THREAD

**Issue by CristhianCarmona** [eloipuertas/ES2014B#69]
Descripción: se ha de construir un escenario donde se enfrentaran los NPC's y el PP, el cual incluirá prefabs hechos en la issues #65 y #66.

Horas estimadas: 5

Condición de finalizadión: el nuevo escenario deberá permitir el ataque de PP a NPC y viceversa sin ninguna dificultad, salvo los obstáculos propios de éste.

**Comment by xaviml** [comment]
Cómo el personaje principal puede moverse con libertad, el npc también podrá hacerlo. A más es un terreno suficientemente grande como para poder luchar sin problemas. Buen trabajo @cctGitHub. Cierro la issue.
