### ISSUE TITLE
#70 Programar que el pj principal ataqui cos a cos

### ISSUE THREAD

**Issue by aniskhoury** [eloipuertas/ES2014B#70]
Que el personatge principal pugui atacar cos a cos.

12h estimades

Condició de final: Que un cop seleccionat un objectiu, vagi cap allà i ataqui a l'NPC, restant-li vida. Cal tenir un estat del personatge principal (viu, mort, atacant, pausa...). El pj principal només pot atacar en l'estat de viu.  Cridar llibreries de so del PJ ( https://github.com/eloipuertas/ES2014B/wiki/so%20PJ )

**Comment by voriol** [comment]
@anïs quan ataquis, pots utilitzar aquestes llibreries per cridar el so

https://github.com/eloipuertas/ES2014B/wiki/so%20PJ

El dia 21 octubre de 2014 9:52, Anïs Khoury notifications@github.com ha
escrit:

> Que el personatge principal pugui atacar cos a cos.
> 
> 10h estimades
> 
> Condició de final: Que un cop seleccionat un objectiu, vagi cap allà i
> ataqui a l'NPC, restant-li vida. Cal tenir un estat del personatge
> principal (viu, mort, atacant, pausa...). El pj principal només pot atacar
> en l'estat de viu.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/eloipuertas/ES2014B/issues/70.

## 

Atentament,

Víctor Oriol i Aguilar
vkoriol@gmail.com

**Comment by aniskhoury** [comment]
Okis @voriol  !! mercis per l'avís!
