### ISSUE TITLE
Integrate group C as integrator

### ISSUE THREAD

**Issue by xaviml** [eloipuertas/ES2014B#8]
## Descripció

Integrar allò que està en la devel-C a devel.
## Temps estimades

8 hores
## Objectius

Com a integrador he de integrar tot allò que hi ha a devel-C a devel, de tal manera que funcioni allò que s'ha testejat en devel-C (#7) i funcioni amb allò que ja hi havia integrat.

**Comment by xaviml** [comment]
Aquí hem de parlar els integradors (@pherrusa7 y @Mithrandir0x) per decidir l'ordre d'integració en la rama devel. El més encertat és que faci jo sempre el primer merge, perquè conté la base del terreny bàsicament. Després lo seu seria integrar el personatge principal i després NPCs. Però això ho parlem la setmana que ve quan veiem que hi ha per integrar.

**Comment by pherrusa7** [comment]
Em sebla bé l'ordre @xaviml
