### ISSUE TITLE
Creation of a weapon

### ISSUE THREAD

**Issue by Demenus** [eloipuertas/ES2014B#80]
Creation of a spear as weapon for the female character

Estimation: 5h

Ends when: The model have a weapon in her right arm and it will be visible in Unity 3D

**Comment by pherrusa7** [comment]
@Demenus Hauries de posar una condició d'acabament ben definida com: "Que el personatge principal a Unity tingui l'arma incorporada".

**Comment by pherrusa7** [comment]
@Demenus The issue it's closed, but the weapon is in his left arm!
