### ISSUE TITLE
#83 mejora terreno para sprint3

### ISSUE THREAD

**Issue by CristhianCarmona** [eloipuertas/ES2014B#83]
Descripción: mejorar el escenario del sprint2, añadiendo mas elementos, objetos, texturas, skyboxes, y escalando más grande lo actual.

Horas estimadas: 11

Condición de finalización: por lo general todo el escenario debe ser mas grande, la altura de la cámara mas baja, y minimizar los conflictos entre estos dos.

**Comment by CristhianCarmona** [comment]
@Folch cuando puedas dime donde y cómo modificas la altura de la cámara, asi voy haciendo pruebas. Si es muy complicado me lo explicas en persona ;)

**Comment by Folch** [comment]
El script de la camara @cctGitHub  es el de CameraMovement.cs, para ver la altura fijate en la posición 1 del vector "posCamera" que es donde se modifica el eje y.

**Comment by xaviml** [comment]
@cctGitHub no hace falta que pongas el número de la issue, github ya lo pone por ti XD jajaja

**Comment by CristhianCarmona** [comment]
@Folch intenta ajustar la nueva cámara a estas perspectivas.
1ra imagen es como se ve actualmente
Las dos ultimas es lo que queremos, solo ajusta el zoom/altura. La inclinación debe ser igual o muy parecida a la actual.

![actual](https://cloud.githubusercontent.com/assets/6708224/4875721/9c0a310e-62a4-11e4-8eb7-5358775ae6d4.PNG)

**Comment by Folch** [comment]
Vale @cctGitHub , cuando pueda la modifico para que quede así

**Comment by xaviml** [comment]
Según los daily meetings esta issue no està acabada, cierto? La passo para el siguiente sprint. @cctGitHub

**Comment by CristhianCarmona** [comment]
@xaviml ya está acabada. Se puede cerrar
PD: el skybox lo tiene que añadir el de la cámara.

**Comment by xaviml** [comment]
Lo del skybox el de la càmera? Hablalo con él. Para el próximo sprint se hace. Cierro esta issue. @cctGitHub
