### ISSUE TITLE
Create Idle Animation

### ISSUE THREAD

**Issue by Payetus** [eloipuertas/ES2014B#89]
## Description

Creates an Idle animation for the Main Character. Idle animations refer to animations within video games that occur when the player character does not do any action (hence being idle). The animation is created to make the game more realistic.
## Objectius
- [ ] Creates an Idle animation for the Main Character.
## Test Case
- [ ] When the character is not doing any action the Idle Animation is Reproduced. 
## Estimated Time

Estimated time: 8 hours
## ProductBacklog

No product backlog

**Comment by pherrusa7** [comment]
@Payetus Això és del 1er Sprint, però està fet i queda tancat.
