### ISSUE TITLE
#91 Create an api to share features between characters, npcs,...

### ISSUE THREAD

**Issue by xavierfebrer** [eloipuertas/ES2014B#91]
Create an api to share features between characters, npcs,...

// todo add description after

**Comment by JordiRQ** [comment]
@xavierfebrer, @Mithrandir0x, @aniskhoury , @Folch

**Comment by xaviml** [comment]
![10155683_10203917398868711_6676943625354728679_n](https://cloud.githubusercontent.com/assets/3974003/5001673/b1d274be-69f8-11e4-9d7f-da0c3329d92f.jpg)

@Mithrandir0x y @pherrusa7 doneu per finalitzada aquesta issue? S'ha implementat al 100% aquesta interficie?

**Comment by pherrusa7** [comment]
@aniskhoury Falten hores, descripció i condicions d'acabament. No puc tancar-la.

**Comment by Mithrandir0x** [comment]
The API has been verified to work (Xavi has done a hell of a job to get it working), and it is used to implement interactions between the player, and the NPCs.

Closing the damn thing...
