### ISSUE TITLE
Programar escollir màgia

### ISSUE THREAD

**Issue by aniskhoury** [eloipuertas/ES2014B#93]
Per tal de dotar de poders al personatge principal s'afegirà en aquest sprint tres màgies en el hud les quals canviaran de textura si l'usuari en selecciona una.

6 hores estimades

US49 - As a user I want to see the main character current selected spell.

Condició sortida: Obtenir del la clase que controla al personatge principal la màgia seleccionada, si no es selecciona cap m'haurien de donar un -1. S'han de veure tres imatges de les màgies en el hud.

**Comment by CristhianCarmona** [comment]
@Folch cuantas horas tienes estimada para esta?

**Comment by Folch** [comment]
6 horas @cctGitHub , pero aun tengo que concretar con @aniskhoury algunas cosas de esta issue.

**Comment by Folch** [comment]
@aniskhoury , tu hauries  (tu perque no té res a veure amb el hud) d'agafar del teclat la màgia seleccionada i fer que en el següent atac que s'ataqui amb ella. Jo t'agafaré amb algun mètode de tipus GET la màgia seleccionada i canviaré la textura corresponent.

**Comment by xaviml** [comment]
Cadascú s'ha d'obrir les seves issues i autoasignarseles nois. @Folch, @aniskhoury

**Comment by xaviml** [comment]
Dono per acabada aquesta issue, tot que en @Roka0006 ha de possar les textures a la magia, perquè no es distingeix que són els números.
