### ISSUE TITLE
Programar millora de càmera

### ISSUE THREAD

**Issue by Folch** [eloipuertas/ES2014B#99]
La càmera ha de veure en tot moment al personatge principal en 3a persona.

5 hores estimades

Condició de finalització: que la càmera segueixi el personatge principal en 3a persona veient-lo sempre i si cal, limitar o eliminar el zoom (que no es demanava igualment) per tal d'oferir una millor vista del personatge (i per evitar possibles problemes)

Edito hores estimades per aquest sprint 4:
8 hores estimades

Edito condició de finalització per aquest sprint 4:
Partint de la càmera del sprint 2, s'ha de poder veure el personatge principal a través de les parets que es posaran transparents (han de ser curtes per a que funcioni bé)

**Comment by xaviml** [comment]
Dono per tancada aquesta issue, tot i que crec que la càmera estava millor en l'sprint 2, et donava més visió de l'escenari. @Folch

**Comment by xaviml** [comment]
@Folch  yorno a obrir la issue, al integrar amb el personatge principal dóna voltes i ha donat molts problemes. Hem integrat la càmera vella. Per solucionar aquest issue en el següent sprint, coloca la càmera fora del prefab del player principal.

**Comment by Folch** [comment]
@xaviml he editat les hores i condicio de finalitzacio d'aquesta issue per aquest sprint 4, ho he editat aquí ja que s'ha quedat oberta però les condicions han canviat

**Comment by xaviml** [comment]
Perfecto, aunque se tienen que hacer las paredes más estrechas, ya que la transparencia no se ve siempre. Por eso se ha creado la issue #168 no @cctGitHub?
